---
title: "K-mean with label, 109 users"
author: "DacDinh"
date: "6/13/2018"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Cài đặt package

```{r}



```

Đi load dữ liệu đầu vào là 109 users với nhãn đã được đính sẵn

```{r}
# label = 1
library(readxl)
advo  <- read_excel("~/DacDinh/K-mean with label, 109 user/Output_1.1 (label).xlsx",
                    sheet = "Advo_label")

# label = 2
retail <- read_excel("~/DacDinh/K-mean with label, 109 user/Output_1.1 (label).xlsx",
                    sheet = "Retail_label")

# label = 3
kol <- read_excel("~/DacDinh/K-mean with label, 109 user/Output_1.1 (label).xlsx",
                    sheet = "KOL_label")

# label = 4
neutral <- read_excel("~/DacDinh/K-mean with label, 109 user/Output_1.1 (label).xlsx",
                    sheet = "Neutral_label")

```



Đi biến đổi dữ liệu

```{r}
library(dplyr)

check = rbind(advo, retail, kol, neutral)
comp = check %>% select(Passion_Point, Content_Creation ,Amplification, Brand_Advo)
comp = as.data.frame(scale(comp, center = T, scale = T))
```



Chạy k-mean với n= 25, chọn ra 4 nhóm

```{r}
f4 = comp %>% select(Passion_Point, Content_Creation, Amplification)

k <- kmeans(f4, 4, nstart=25, iter.max=1000)

library(RColorBrewer)
library(scales)
palette(alpha(brewer.pal(9,'Set1'), 0.5))
plot(f4, col=k$clust, pch=16)

# cluster
# Cluster sizes
sort(table(k$clust))
clust <- names(sort(table(k$clust)))


#plot 3d
#library(rgl)
#plot3d(data$Passion_Point, samsung$Content_Creation, samsung$Amplification, type = "s", size = .7, col = brewer.pal(4, "Dark2")[k$cluster] )

# cluster
nhom1 = check[row.names(check[k$clust==4,]),] %>% select(ID, Passion_Point, Content_Creation, Amplification, Brand_Advo, Label )

nhom2 = check[row.names(check[k$clust==2,]),] %>% select(ID, Passion_Point, Content_Creation, Amplification, Brand_Advo, Label)

nhom3 = check[row.names(check[k$clust==1,]),] %>% select(ID, Passion_Point, Content_Creation, Amplification, Brand_Advo, Label)

nhom4 = check[row.names(check[k$clust==3,]),] %>% select(ID, Passion_Point, Content_Creation, Amplification, Brand_Advo, Label)
```

Xem dữ liệu các nhóm

```{r}
nhom1
nhom2
nhom3
nhom4
```

```{r}
View(nhom1)
View(nhom2)
View(nhom3)
View(nhom4)
```



```{r}
plot(mtcars$mpg)
```

